@baseUrl = http://localhost:3000

### Register User
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "sandhiya",
    "password": "123"
}

### Login User
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "sandhiya",
    "password": "123"
}

### Add Note (replace {{token}} with your JWT token from the login response)
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNDI3NDE0MywiZXhwIjoxNzM0Mjc3NzQzfQ.aYtRhBDqZei_MkUfn0Rw8EVF5RxtLfLsgpUQXwX26Nw

{
    "title": "My First Note",
    "content": "This is the content of my First note."
}

### Get All Notes (replace {{token}} with your JWT token)
GET {{baseUrl}}/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNDI3NDE0MywiZXhwIjoxNzM0Mjc3NzQzfQ.aYtRhBDqZei_MkUfn0Rw8EVF5RxtLfLsgpUQXwX26Nw

### Update Note (replace {{token}} and note ID in the URL)
PUT {{baseUrl}}/notes/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNDI3NDE0MywiZXhwIjoxNzM0Mjc3NzQzfQ.aYtRhBDqZei_MkUfn0Rw8EVF5RxtLfLsgpUQXwX26Nw

{
    "title": "Updated First Note Title",
    "content": "Updated content for this note."
}

### Delete Note (replace {{token}} and note ID in the URL)
DELETE {{baseUrl}}/notes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNDI3NDE0MywiZXhwIjoxNzM0Mjc3NzQzfQ.aYtRhBDqZei_MkUfn0Rw8EVF5RxtLfLsgpUQXwX26Nw
