name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - deploy  # Trigger the workflow when changes are pushed to the main branch

env:
  # Define environment variables for Docker Hub login credentials
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: notes-taking-api  # Your Docker Hub repository name
  TAG: latest  # Tag for the image, could be 'latest' or use the Git commit SHA
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up Docker Buildx (for building multi-platform images if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USER/$IMAGE_NAME:$TAG .
    
    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push $DOCKER_USER/$IMAGE_NAME:$TAG

